name: Java-CI-Pipeline.yml

on:
  workflow_dispatch: 

env:
  JF_URL: https://trialj8vw48.jfrog.io
  JF_TOKEN: ${{ secrets.JFROG_TOKEN }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
