name: build.yml

on: 
 workflow_call:

jobs:
  build:
    runs-on: [self-hosted, aws-ec2-runner]

    steps:
     
    - uses: actions/checkout@v4

    - name: Print Workspace/Runner Details
      run: |
            echo "Workspace Path: $GITHUB_WORKSPACE"
            echo "Runner Temporary Directory: $RUNNER_TEMP"
            echo "Contents of Workspace:" ls -l $GITHUB_WORKSPACE
            echo "GitHub Runner OS: $RUNNER_OS"
            echo "Runner Name: $RUNNER_NAME"
            echo "Run ID: $GITHUB_RUN_ID"
            echo "Run Number: $GITHUB_RUN_NUMBER
          
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
    - name: Build with Maven
      run: mvn clean install

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: target/*.jar

    - name: Setup Node.js
      uses: actions/setup-node@v4

   
