name: image_push

on:
 workflow_call:

env:
  DOCKER_IMAGE: surendradockerid19/petapp:${{ github.sha }}

jobs:
  image_push:
    runs-on: [self-hosted, aws-ec2-runner]
   
    steps:
     - name: Clean up Docker system
       run: |
         docker system prune -af
    
     - name: BUILD DOCKER IMAGE
       run: |
         sudo docker build -t ${{ env.DOCKER_IMAGE }} .
         sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar
 
     - name: UPLOAD DOCKER IMAGE ARTIFACT
       uses: actions/upload-artifact@v4
       with:
         name: docker-image
         path: docker_image.tar
 
     - name: LOG IN TO DOCKER HUB
       run: echo "Testing1!" | sudo docker login -u "surendraqa10@gmail.com" --password-stdin
       #run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
     - name: PUSH DOCKER IMAGE
       run: sudo docker push ${{ env.DOCKER_IMAGE }}

     
