name: Java-CI-Pipeline.yml

on:
  workflow_dispatch: 

env:
  JF_URL: https://trialj8vw48.jfrog.io
  JF_TOKEN: ${{ secrets.JFROG_TOKEN }}

  DOCKER_IMAGE: surendradockerid19/petapp:${{ github.sha }}
  MAVEN_OPTS: "-DskipTests=true"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit
     
  test:
       uses: ./.github/workflows/test.yml
       needs: sonar
       secrets: inherit
      
  image_push:
       uses: ./.github/workflows/test.yml
       needs: test
       secrets: inherit 
   
