name: Java CI Pipeline [Self Hosted Runner]

on:
  workflow_dispatch: 

env:
  JF_URL: https://trialj8vw48.jfrog.io
  JF_TOKEN: ${{ secrets.JFROG_TOKEN }}

  DOCKER_IMAGE: surendradockerid19/petapp:${{ github.sha }}
  MAVEN_OPTS: "-DskipTests=true"

jobs:
  clean_ws:
    uses: ./.github/workflows/clean_ws.yml
    secrets: inherit
    
  build:
    uses: ./.github/workflows/build.yml
    needs: clean_ws
    secrets: inherit
      
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit
     
  test:
       uses: ./.github/workflows/test.yml
       needs: sonar
       secrets: inherit
      
  image_push:
       uses: ./.github/workflows/image_push.yml
       needs: test
       secrets: inherit 
   
