name: Java-CI-Pipeline-Inbuilt-Runner.yml

on:
  workflow_dispatch:  # Manual trigger

env:
  JF_URL: https://trialj8vw48.jfrog.io
  JF_TOKEN: ${{ secrets.JFROG_TOKEN }}
  DOCKER_IMAGE: surendradockerid19/petapp:${{ github.sha }}

jobs:
  #Checkout -->Install JDK -->Cache Maven Dependencies -->Build -->Sonar Scan -->Test (upload) -->Docker push -->JFrog
  build:                                            
    runs-on: ubuntu-latest
    
    steps:
    - name: PRINT THE RUNNER NAME
      run:  echo "Runner name is $RUNNER_NAME"
          
    - name: CHECKOUT CODE
      uses: actions/checkout@v4

    - name: SET UP JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: CACHE MAVEN DEPENDENCIES
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
    - name: BUILD WITH MAVEN
      run: mvn clean install

    - name: UPLOAD BUILD ARTIFACTS
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/*.jar

    - name: SonarCloud SCAN
      run: mvn sonar:sonar -Dsonar.projectKey=surendradire_java-ci-gihub -Dsonar.organization=demo-org-key -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2f515f13fa1f66d8619b8f604c87e2bacc7a8bc3 -Dsonar.java.binaries=target/classes

    - name: RUN UNIT TEST
      run: mvn test

    - name: UPLOAD TEST RESULTS
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/test-classes/TEST-*.xml

    # START: DOCKER IMAGE AND PUSH
    - name: BUILD DOCKER IMAGE
      run: |
        sudo docker build -t ${{ env.DOCKER_IMAGE }} .
        sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

    - name: UPLOAD DOCKER IMAGE ARTIFACT
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: docker_image.tar

    - name: LOG IN TO DOCKER HUB
      run: echo "Testing1!" | sudo docker login -u "surendraqa10@gmail.com" --password-stdin
      #run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: PUSH DOCKER IMAGE
      run: sudo docker push ${{ env.DOCKER_IMAGE }}

      # END: DOCKER IMAGE AND PUSH
      
    - name: SETUP Node.js
      uses: actions/setup-node@v4

    - name: INSTALL AND CONFIGURE JFROG CLI
      run: |
        npm install -g jfrog-cli-v2-jf
        echo ${{ secrets.JFROG_TOKEN }} | jf c add --interactive=false --url=https://trialj8vw48.jfrog.io --access-token-stdin

    - name: CONFIGURE JFrog CLI WITH ACCESS TOKEN OR USERNAME/PASSWORD
      run: |
        jf config add artifactory-server \
          --url="https://trialj8vw48.jfrog.io" \
          --user="admin" \
          --password="Admin123!" \
          
    - name: UPLOAD JAR TO JFrog
      run: |
        #jf config add artifactory-server --artifactory-url="https://trialj8vw48.jfrog.io" --user="admin" --password="Admin123!" --interactive=false
        #echo ${{ secrets.JFROG_TOKEN }} | jf c add --interactive=false --url=https://trialj8vw48.jfrog.io --access-token-stdin
        sudo jf rt u "target/*.jar" "/artifactory/repo-test/"  --url="https://trialj8vw48.jfrog.io" --user "admin" --password="Admin123!"

     
