name: test123


on: [push]


jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   # This action checks out the code from the repository
   - name: Checkout Code
     uses: actions/checkout@v2


   # This action sets up the JFrog CLI with Artifactory URL and    a predefined Artifactory oidc integration name
   - uses: jfrog/setup-jfrog-cli@v4
     with:
          oidc-provider-name: <oidc integration name>
     env:
       JF_URL: https://trialj8vw48.jfrog.io/
       #JF_PROJECT: ${{ vars.JF_PROJECT }} # optional variable

      
   # This action sets up the JFrog CLI with the Artifactory URL and access token     
   - uses: jfrog/setup-jfrog-cli@v4
     env:
       JF_URL: https://trialj8vw48.jfrog.io/
       JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }} 

   # This command adds a new server configuration to the JFrog CLI, as an alternative for using the setup-jfrog-cli action    
   - run: |
       export SERVER_ID="test"
       jf c add $SERVER_ID --url=https://trialj8vw48.jfrog.io/ --access-token=${{ secrets.JFROG_TOKEN }}  --interactive=false


   # This action creates a new test file and uploads it to Artifactory, if build_name and build_number are omitted GitHub run default are used     
   - name: Push Build to Artifactory
     run: |
       echo "test file " > test.txt
       export BUILD_NAME="my-build"
       export BUILD_MODULE="my-module"
       export BUILD_NUMBER="1"


    
