name: Java CI with Maven surendra

on:
  workflow_dispatch:  # This enables manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Print runner name
      run: |
          echo "Runner name is $RUNNER_NAME"
     
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
    - name: Build with Maven
      run: mvn clean install

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/*.jar

    #- name: SonarCloud Scaning
      #run: mvn sonar:sonar -Dsonar.projectKey=surendradire_java-ci-gihub -Dsonar.organization=demo-org-key -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2f515f13fa1f66d8619b8f604c87e2bacc7a8bc3

    - name: Set up JFrog CLI
      run: |
        curl -fL https://getcli.jfrog.io | sh
        sudo mv jfrog /usr/local/bin/
        #cd /usr/local/bin/
        sudo jf --version
    
    - name: Configure JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
        JF_URL: https://trialj8vw48.jfrog.io/
        JF_ACCESS_TOKEN: cmVmdGtuOjAxOjE3Njk2NzQ1OTE6OEVVWUprVVhQQzhQQ25vbldxMFBJNHpoV2Rm
    - name: Upload JAR to JFrog
      run: |
         sudo jf rt u "target/*.jar" "repo-test/"     
