name: Sonar Scan

on:
  workflow_dispatch: 

env:
  JF_URL: https://trialj8vw48.jfrog.io
  JF_TOKEN: ${{ secrets.JFROG_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: SonarCloud Scaning
      run: mvn sonar:sonar -Dsonar.projectKey=surendradire_java-ci-gihub -Dsonar.organization=demo-org-key -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2f515f13fa1f66d8619b8f604c87e2bacc7a8bc3
