
name: CI 4 self hosted runners

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:  # This enables manual trigger
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, my-ec2-runner]

    steps:
    - name: Print runner name
      run: echo "Runner name is: $RUNNER_NAME"

    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
    - name: Build with Maven
      run: mvn clean install

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/*.jar

    - name: SonarCloud Scaning
      run: mvn sonar:sonar -Dsonar.projectKey=surendradire_java-ci-gihub -Dsonar.organization=demo-org-key -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2f515f13fa1f66d8619b8f604c87e2bacc7a8bc3

      
